plugins: rubocop-rspec

AllCops:
  CacheRootDirectory: tmp/rubocop_cache
  NewCops: enable
  SuggestExtensions: true
  TargetRubyVersion: 4.0

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "spec/**/*"

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 10

Naming/PredicateMethod:
  AllowedMethods:
    - apply
    - call

RSpec/ExampleLength:
  Max: 45

RSpec/MultipleExpectations:
  Max: 10

RSpec/SpecFilePathFormat:
  CustomTransform:
    GitHub: github
  Exclude:
    - "spec/integration/**/*"
    - "spec/live/**/*"
